{
    "name": "Hospital Management",
    "version": "17.0.0.0.0",
    "category": "",
    "summary": "",
    "author": "Odoo Mates",
    "description": """""",
    "sequence": -100,
    "license": "LGPL-3",
    "depends": ["base"],
    "data": ["views/menu.xml"],
    "demo": [],
    "application": True,
    "installable": True,
    "auto_install": False,
}
